image:
  repository: ghcr.io/gkalian/amuzing-file-browser
  tag: ""
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80

resources: {}

podSecurityContext:
  enabled: true
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

securityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: filebrowser.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: false
  # type can be "pvc" or "hostPath"
  type: pvc
  # PVC settings (used when type: pvc)
  size: 10Gi
  storageClass: ''
  accessModes:
    - ReadWriteOnce
  # Common mount path inside the container
  mountPath: /data
  # hostPath settings (used when type: hostPath)
  hostPath:
    path: /srv/amuzing-filebrowser/data
    # One of: DirectoryOrCreate, Directory, FileOrCreate, File, Socket, CharDevice, BlockDevice
    type: DirectoryOrCreate

env:
  FILEBROWSER_ROOT: /data
  PORT: '8080'
  LOG_LEVEL: 'info'
